src/objects/A__c.object
<CustomObject>
    <label>A</label>
    <nameField>
        <label>A name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/C__c.object
<CustomObject>
    <fields>
        <fullName>C_to_A__c</fullName>
        <label>C to A</label>
        <referenceTo>A__c</referenceTo>
        <relationshipLabel>C</relationshipLabel>
        <relationshipName>C</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>C</label>
    <nameField>
        <label>C name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AllParents.cls
/* Parent-Child 3
 *
 *Write a SOQL query on 'A' and retrieve all parents with 
 *all their child records where in child name is 'John'.
 */
 
public class AllParents {
    public AllParents() {
          list<A__c> myList = [Select a.Name, a.Id, 
                               (Select Name From C__r) 
                               From A__c a where  A__c.id 
                               IN (Select A__c
                               from C__c where Name Like '%john%')];
          for(A__c aObj : myList){
              system.debug(aObj);
              for(C__c  cObj: aObj.C__r)
                  system.debug(cObj);
           }
     }
}