src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Line_Item_Id__c</fullName>
        <externalId>true</externalId>
        <label>Line Item Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Unique__c</fullName>
        <label>Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DMLOperation.cls
/****************************************************************************
 Class Name: DMLOperation
 Created Date:14/7/2015
 Description: This class displays record of opportunity having amount
				greater than 10000
*****************************************************************************/ 
public class DMLOperation {
    //inserting record to lead
     public void DMLInsertRecord(){
     	List<Lead> Llistof100 = new List<Lead>(); 
      	for(Integer i=0; i<100 ;i++){ 
        	Lead leadL = new Lead(LastName='Test100'+i, Company='Test1 Inc.',
        	Status='Status changed', Unique__c= 'abc'+i);
        	Llistof100.add(leadL);
     	}
     try {
         insert Llistof100;
     }
     catch(DMLException e){ 
        Logs__c error =new Logs__c(Error__c = e.getMessage());
  		insert error;
        System.debug('The following exception has occurred: ' + e.getMessage());
       }
    }
    //deleting record fron account which are inactive 
	public void DMLdeleteInactiveRecord() {
  		List<Account> accountList= [Select id, name from Account Where Active__c ='No' And CreatedDate = LAST_90_DAYS];
    	if(accountList!=null && accountList.size()>0){
    	   for(Account a:accountList ) {  
        	   System.debug(a);
    	   }
    	}
    	else{
            system.debug('Records not found');
        }
     Delete accountList;  
  }
    //upserting records to aseet
	public void assetRecord(){
    	list<Asset> assetlist =  new list<Asset>();
        for(integer i=0;i<4;i++){
            assetlist.add(new Asset(Name='ABC welcome'+i,Line_Item_Id__c='DEF'+i,AccountId='00128000004UkTX'));
        }
        try{
            upsert assetlist Line_Item_Id__c;
           }
    
    catch(Exception e){
    	system.debug('Exception Occured:'+e);
        }
    }
}