src/objects/Employee__c.object
<CustomObject>
    <description>This is child object  of Project Details containing info about employee</description>
    <fields>
        <fullName>First_name__c</fullName>
        <description>Mandatory</description>
        <label>First name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{000000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Abc.cls
public  without sharing class Abc {
    public void empFunction() {
       
        list<Employee__c> empList=[Select e.First_Name__c 
                              From Employee__c e];
       	
        
       system.debug(empList.size());
       system.debug(empList);
       
    }
}


/*

with sharing both classes  with private owd

Employee__c:{First_Name__c=Manager 2, Id=a0I28000000KtdFEAS}, 
Employee__c:{First_Name__c=Manager 1, Id=a0I28000000KtcMEAS}, 
Employee__c:{First_Name__c=Manager 3, Id=a0I28000000KtiKEAS}, 
Employee__c:{First_Name__c=HR 1, Id=a0I28000000KthvEAC})





*/