src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Unique_field__c</fullName>
        <label>Unique field</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Logs__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Logs</label>
    <nameField>
        <label>Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadInsert.cls
public class LeadInsert {
    public LeadInsert() {
        List<Lead> leadl = new List<Lead>(); 
        Integer j=0;
        while(j<2) {
            for(Integer i=0; i<5 ; i++) { 
                Lead listLead = new Lead(LastName='qwerty11'+i, Company='Test',
                                LeadSource='Open - Not Contacted', Unique_Field__c= 'abc11'+i);
                leadl.add(listLead);
                System.debug(leadl);
            }//for
            j++;
        }//while
      if((leadl.size()!= 0) ) {
            //partial insert
            Database.SaveResult[] srList = Database.insert(leadl,false);
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                }
                else {
                //Operation failed, so get all errors
                    for(Database.Error err : sr.getErrors()) {
                        Logs__c error =new Logs__c();
                        error.Name='Errrrroooorrrr';
                        error.Error__c=err.getMessage();
                        insert error;
                    }
                }
            }
         }
    }
}